# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Huacheng SONG" # "Lorem ipsum"
description              : "🦒 Welcome to the Academicland of Floret Huacheng SONG! Looking forward to sharing insights with you!
"
repository               : "florethsong/florethsong.github.io"
google_scholar_stats_use_cdn : true

# google analytics
google_analytics_id      :  true # get google_analytics_id from https://analytics.google.com/analytics/

# SEO Related
google_site_verification :  false # get google_site_verification from https://search.google.com/search-console/about
bing_site_verification   :  false # get bing_site_verification from https://www.bing.com/webmasters/about
baidu_site_verification  :  false # get baidu_site_verification from https://ziyuan.baidu.com/login/index?u=/site/index

# Site Author
author:
  name             : "Huacheng SONG"
  avatar           : "images/android-chrome-512x512.png"
  bio              : #"Hi! I'm Huacheng SONG, currently a second-year PhD student in Computational Linguistics in the Department of Language Science and Technology at the Hong Kong Polytechnic University. I am fortunate to be jointly supervised by Prof. Che-Ren HUANG and Prof. Emmanuele CHERSONI.<br>My most recent research interest lies in the interpretability of generative language models, specifically on probing into the “machine psychology” and computational creativity embedded in these models through the lenses of psycholinguistics and cognitive linguistics.<br>Prior to my PhD study, I received my MA from Shanghai International Studies University, where I was advised by Prof. Hongzhi XU and working on multiword expression- and creativity-aware machine translation and the development of its corresponding evaluation metrics.<br>Outside of research, I enjoy biking, hiking, and skiing and explore cities for something fresh to me!"
  location         : "Hong Kong, China"
  employer         :
  pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=pljOT4sAAAAJ&hl"
  email            : "shc0366@gmail.com"
  researchgate     : "https://www.researchgate.net/profile/Huacheng-Song?ev=hdr_xprf&_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6ImxvZ2luIiwicGFnZSI6ImhvbWUiLCJwcmV2aW91c1BhZ2UiOiJsb2dpbiIsInBvc2l0aW9uIjoiZ2xvYmFsSGVhZGVyIn19"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "florethsong" # e.g., "github username"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : # e.g., "https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : #"Floret Huacheng Song" # e.g., "linkedin username"
  dblp             : #"https://dblp.org/pid/325/4598.html" # e.g., "https://dblp.org/pid/xx/xxxx.html"
  orcid            : "https://orcid.org/my-orcid?orcid=0009-0007-9915-3398" # e.g., "https://orcid.org/xxxx"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
